DROP TABLE IF EXISTS notify_events CASCADE;
DROP TRIGGER IF EXISTS trg_enforce_trigger_type_permissions ON workflow_triggers;
DROP FUNCTION IF EXISTS public.enforce_trigger_type_permissions();
DROP TRIGGER IF EXISTS trg_enforce_step_type_permissions ON workflow_steps;
DROP FUNCTION IF EXISTS public.enforce_step_type_permissions();
DROP FUNCTION IF EXISTS public.ensure_quota_period(uuid);
DROP FUNCTION IF EXISTS public.has_org_role(uuid, uuid, member_role[]);
DROP FUNCTION IF EXISTS public.is_org_member(uuid, uuid);
DROP FUNCTION IF EXISTS public.user_org_role(uuid, uuid);
DROP VIEW IF EXISTS org_usage_stats;
DROP TABLE IF EXISTS workflow_results CASCADE;
DROP TABLE IF EXISTS watched_events CASCADE;
DROP TABLE IF EXISTS step_runs CASCADE;
DROP TABLE IF EXISTS workflow_runs CASCADE;
DROP TABLE IF EXISTS workflow_triggers CASCADE;
DROP TABLE IF EXISTS workflow_steps CASCADE;
DROP TABLE IF EXISTS workflows CASCADE;
DROP TABLE IF EXISTS org_members CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
DROP TYPE IF EXISTS step_run_status;
DROP TYPE IF EXISTS run_status;
DROP TYPE IF EXISTS trigger_type;
DROP TYPE IF EXISTS step_type;
DROP TYPE IF EXISTS member_role;
